###
post http://localhost:2025/creaetuser
Content-Type: application/json

{
    "username":"admin",
    "password":"admin",
    "email":"admin@gmail.com",
    "role":"admin",
    "phone":"085161671965"
}

###
post http://localhost:2025/creaetuser
Content-Type: application/json

{
    "username":"user",
    "password":"user",
    "email":"user@gmail.com",
    "role":"user",
    "phone":"085161671965"
}

###
post http://localhost:2025/creaetuser
Content-Type: application/json

{
    "username":"user2",
    "password":"user2",
    "email":"user2@gmail.com",
    "role":"user",
    "phone":"085161671965"
}

###
post http://localhost:2025/login 
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}

###
post http://localhost:2025/login 
Content-Type: application/json

{
    "username":"user",
    "password":"user"
}

###
post http://localhost:2025/login 
Content-Type: application/json

{
    "username":"bimoemail",
    "password":"k1gn7des"
}

###
post http://192.168.100.18:2025/register
Content-Type: application/json

{
    "username":"bimoemail",
    "email": "bimowahyu1908@gmail.com",
    "phone": "085161671965"

}

###
get http://localhost:2025/getuser

###
get http://localhost:2025/me 

###
get http://localhost:2025/getbooking

###
post http://localhost:2025/updatekategori/1
Content-Type: application/json

{
   "namaKategori": "Umroh"
}

###
get http://localhost:2025/getkategori

###
post http://localhost:2025/createbooking
Content-Type: application/json

{
    "wisataId": "2",
    "tanggalBooking": "2024-03-12",
    "jumlahOrang": 8
}


###
put http://localhost:2025/updatebooking/1
Content-Type: application/json

{
    "wisataId": "1",
    "tanggalBooking": "2024-02-12",
    "jumlahOrang": 7
}

###
post http://localhost:2025/createtransaksi
Content-Type: application/json

{
  "bookingId": 1
}

###
get http://localhost:2025/getwisata/2

###
get http://localhost:2025/getbooking/1

###
get http://localhost:2025/getbooking


###
get http://localhost:2025/getkonfigurasi

###
get http://localhost:2025/getslide/1